product:
  label: product
  replicas: 1
  containerPort: 9010
  image: k3d-lab05-ecommerce-reg:5000/ecommerce/product-service:lab05
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 9010

secret:
  label: product-secret
  SPRING_DATA_MONGODB_URI_PRODUCT: PROVIDED_VIA_GITHUB_ACTIONS

config:
  label: product-config-map
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-svc:80/eureka/
  EUREKA_INSTANCE_HOSTNAME: product-svc