web:
  label: web-app
  replicas: 1
  containerPort: 80
  image: k3d-lab05-ecommerce-reg:5000/ecommerce/web-app:lab05
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 80
    