registry:
  label: registry
  replicas: 1
  containerPort: 8761
  image: k3d-lab05-ecommerce-reg:5000/ecommerce/service-registry:lab05
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 80
  averageUtilization:
   cpu: 60
   memory: 60
  
    
