user:
  label: user
  replicas: 1
  containerPort: 9050
  image: k3d-lab05-ecommerce-reg:5000/ecommerce/user-service:lab05
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
  averageUtilization:
   cpu: 60
   memory: 60
  service:
    type: ClusterIP
    port: 9050

secret:
  label: user-secret
  SPRING_DATA_MONGODB_URI_USER: "mongodb+srv://lab05admin:<db_password>@lab05-ecommerce-cluster.q1ldfli.mongodb.net/purely_user_service?retryWrites=true&w=majority&appName=lab05-ecommerce-cluster"

config:
  label: user-config-map
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://registry-svc:80/eureka/
  EUREKA_INSTANCE_HOSTNAME: user-svc